apiVersion: v1
kind: Service
metadata:
  name: fashion-style
  namespace: fashion-style
spec:
  type: NodePort
  selector:
    app: fashion-style
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
